### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by brunosiqueira** [ClementTANGUY/myluxee.com#1]
-Create model classes and its proper associations.

**Comment by ClementTANGUY** [comment]
Bruno, I will sent tomorrow wednesday 7/10 from a PC the A to Z brands names file to seed in the base

**Comment by brunosiqueira** [comment]
No problem, @ClementTANGUY. I will create the database structure meanwhile

**Comment by ClementTANGUY** [comment]
Sorry for disturbing you Bruno, but don't forget in the base structure that a sales associates rather be able to select existing stores in his sign up than fill in new information ´cause a store could already exist in the base and we must not have two different sales associates working in the same store registering two different address....

**Comment by brunosiqueira** [comment]
I think I'll use an autocomplete form. If the sales finds the store, he can use. Otherwise, he will crete a new one.

Or we can have a "Check the store already registered here!" - "Could not find your store? Register it right now!"

**Comment by ClementTANGUY** [comment]
You're a chief Bruno! I completely trust you
