### ISSUE TITLE
Store CRUD

### ISSUE THREAD

**Issue by brunosiqueira** [ClementTANGUY/myluxee.com#8]
-the brands are pre-existing data? Are they recorded already? We might need to create an script to record them in the database 
-Create store CRUD (T_Store) 
-create/update form 
-show store details
-List associated sales
-Show summary of sales 
-List news (where ill the news be created?)

**Comment by ClementTANGUY** [comment]
Concerning your last question, on a store full profile, I would only like the sales associates registered for this specific store to be allowed to add pictures of it and to edit directly its latest news by a few lines comment (ex.: "Our store will be closed next Tuesday for inventory" or "We are organising a special event Thursday evening for..."...) 
Same thing for a sales on its own full profile (ex.: "I moving to Hermes. A new challenge for me. See you there!")
